name: Twice Weekly Claude Run

on:
  schedule:
    - cron: '0 12 * * Mon,Thu'
  workflow_dispatch:

jobs:
  run_claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Claude
        env:
          EIP_API_KEY: ${{ secrets.EIP_ANTHROPIC_API_KEY }}
          EIP_SLACK_TOKEN: ${{ secrets.EIP_SLACK_TOKEN }}
          EIP_SLACK_CHANNEL_ID: ${{ secrets.EIP_SLACK_CHANNEL_ID }}
        run: |
          python claude.py